server.port: 8081

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root
    password: password-1

  application:
    name: album-service

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  endpointUrl:
  accessKey:
  secretKey:
  bucketName:

security:
  basic:
    enabled: false
